case_name: cylinder_A_20260126-150952
geometry:
  output_file: geometry.txt
  stl_file: C:/Users/GAI/Desktop/Scott/taichi_LBM3D/cases/cylinder.stl
  voxel_size: 0.1
run_mesh: true
run_simulation: true
simulation:
  bc_x_left:
    rho: 1.0
    type: 2
    vx: 0.01
    vy: 0.0
    vz: 0.0
  bc_x_right:
    rho: 1.0
    type: 1
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_y_left:
    rho: 1.0
    type: 0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_y_right:
    rho: 1.0
    type: 0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_z_left:
    rho: 1.0
    type: 0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_z_right:
    rho: 1.0
    type: 0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  fx: 1.0e-05
  fy: 0.0
  fz: 0.0
  input_file: C:\Users\GAI\Desktop\Scott\taichi_LBM3D\cases\geometries_for_batch\cylinder_A.txt
  max_timestep: 50000
  niu: 0.01
  nx: 74
  ny: 74
  nz: 90
  output_frequency: 1000
  vtk_frequency: 10000
  zarr_data_path: zarr_data
  zarr_output_frequency: 100
