case_name: cylinder_test
run_mesh: true
run_simulation: true
geometry:
  stl_file: C:/Users/GAI/Desktop/Scott/taichi_LBM3D/cases/cylinder.stl
  output_file: geometry.txt
  voxel_size: 0.1
simulation:
  input_file: geometry.txt
  nx: 74
  ny: 74
  nz: 90
  niu: 0.01
  fx: 1.0e-05
  fy: 0.0
  fz: 0.0
  bc_x_left:
    type: 2
    rho: 1.0
    vx: 0.01
    vy: 0.0
    vz: 0.0
  bc_x_right:
    type: 1
    rho: 1.0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_y_left:
    type: 0
    rho: 1.0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_y_right:
    type: 0
    rho: 1.0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_z_left:
    type: 0
    rho: 1.0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  bc_z_right:
    type: 0
    rho: 1.0
    vx: 0.0
    vy: 0.0
    vz: 0.0
  max_timestep: 50000
  output_frequency: 1000
  vtk_frequency: 10000
  zarr_output_frequency: 100
  zarr_data_path: "zarr_data"
